- README.md
> [doc] link: http -> https

- api/String.cpp
A rare but possible null pointer dereference occurs when a String object is destroyed after either a failed initialization or intentional invalidation. Adding a simple `if (buffer)` test before `free`ing it avoids this failure case.
> Add null pointer test to String destructor

- api/Print.h
- api/Stream.h
Moved `flush` method to `Print`.
Added `availableForWrite` method to `Print`.
Fix #102
> Some Print / Stream API fixes

- .github/workflows/unit-tests.yml
On every push and pull request that modifies relevant files:
- Run unit tests
- Check for memory leaks
- Print coverage report in the workflow log
- Upload coverage report to Codecov
---
The workflow run in my fork:
https://github.com/per1234/ArduinoCore-API/runs/1165202122
> Add workflow to run unit tests

- api/deprecated-avr-comp/avr/pgmspace.h
Originally, `pgm_read_ptr` used to cast its argument to `const void *`, i.e. a pointer to read-only data.  
This is incorrect, because the argument is a pointer to a pointer in "flash memory". You cannot cast it to
`const void *` and then dereference it, because `void` is not an object type.
Also, the pointer itself is read-only, but the data could in theory be mutable.  
The correct type should be `void *const *`, i.e. a pointer to a read-only pointer to any data.
> Fix pgm_read_ptr in AVR pgmspace.h

- api/ArduinoAPI.h
Hardware related includes can be removed from ArduinoAPI.h since they can be included by the specific interfaces. This gives also the users more flexibility to implement their own classes.
In ArduinoCore-API integration in ArduinoCore-samd, the 3 includes removed form ArduinoAPI.h are, instead, here: 
- [HardwareSerial.h](https://github.com/arduino/ArduinoCore-samd/blob/05db380e9e8524956d66b47b08e3e46596bc6451/cores/arduino/Uart.h#L21)
- [SPI.h](https://github.com/arduino/ArduinoCore-samd/blob/05db380e9e8524956d66b47b08e3e46596bc6451/libraries/SPI/SPI.h#L24)
- [I2C.h](https://github.com/arduino/ArduinoCore-samd/blob/05db380e9e8524956d66b47b08e3e46596bc6451/libraries/Wire/Wire.h#L23)
ArduinoCore-mbed must be modified as well to correctly include this files. This branch …
> Remove include of Hardware*.h from ArduinoAPI.h

- api/HardwareI2C.h
Changing return type of `requestFrom` from `uint8_t` to `size_t` allows the function to return the correct amount of bytes read (since internally it's already a `size_t` which is downcast to a `uint8_t` upon returning it).
Merging this PR also requires to merge
* https://github.com/arduino/ArduinoCore-samd/pull/442
* https://github.com/arduino/ArduinoCore-megaavr/pull/92
* https://github.com/arduino/ArduinoCore-mbed/pull/97
@facchinm Let's coordinate to get this done.
> Fix: Allow HardwareI2C::requestFrom to return values > 256

- api/String.cpp
- api/String.h
- test/src/String/test_String.cpp
> Bugfix: Small buffer size causes buffer overrun when invoking String::Ctor with large float/double value.

- api/RingBuffer.h
- test/src/Ringbuffer/test_available.cpp
- test/src/Ringbuffer/test_availableForStore.cpp
- test/src/Ringbuffer/test_isFull.cpp
- test/src/Ringbuffer/test_read_char.cpp
- test/src/Ringbuffer/test_store_char.cpp
Quick fix with regards to https://github.com/arduino/ArduinoCore-samd/issues/580 .
> Revert changes to RingbufferN

- api/String.cpp
- api/String.h
When working with the Arduino String class, I've found that I couldn't efficiently combine it with some external libraries that explicitely pass char* and length around, without nul-terminating their strings. This prompted me to modify and expose the concat (const char* cstr, unsigned int length) method, add a new String(const char* cstr, unsigned int length) constructor. While I was going over the string class, I found some other minor improvements, which are included here.
This is a port of https://github.com/arduino/Arduino/pull/1936. The commits are  identical, except for some improved commit messages and one commit was dropped since that change was already made by someone else in the meantime.
I've provided some testcases by updating the string examples: …
>  Strings without null-termination

- api/String.cpp
- api/String.h
- test/CMakeLists.txt
- test/src/String/test_move.cpp
The move constructor String::String(String&&) and String::operator=(String&&)
now perform move instead of copy.
Remove String(StringSumHelper&&) constructor because having it makes no sense:
String(String&&) takes care of it - you can pass either String&& or
StringSumHelper&& to this constructor. StringSumHelper is derived from String
and has no data members other than those inherited from String. Even if it did
have some extra data members, truncation would have to happen during move, and
normally that is something you don't want.
> Make String move constructor move instead of copy.

- api/String.cpp
- api/String.h
ref.
https://github.com/esp8266/Arduino/pull/7939
Make sure comments are correct and make it clear to the user that these only return either true or false, and not a numeric value.
> Bool as return value for logical operations

- api/Common.h
- api/HardwareSPI.h
- api/IPAddress.h
- api/Print.h
- api/Stream.h
- api/String.h
Codespell detected a few minor typos in the API headers.  Fix their spelling.
> Fix minor misspellings in comments

- .codespellrc
- .github/workflows/spell-check.yml
- .github/workflows/unit-tests.yml
- README.md
- api/IPAddress.cpp
- api/Udp.h
- api/deprecated-avr-comp/avr/interrupt.h
- api/deprecated/Client.h
- api/deprecated/HardwareSerial.h
- api/deprecated/IPAddress.h
- api/deprecated/Print.h
- api/deprecated/Printable.h
- api/deprecated/Server.h
- api/deprecated/Stream.h
- api/deprecated/Udp.h
- api/deprecated/WString.h
- test/src/Stream/test_readBytes.cpp
- test/src/String/test_replace.cpp
- test/src/String/test_trim.cpp
On every push, pull request, and periodically, use [the `codespell-project/actions-codespell` action](https://github.com/codespell-project/actions-codespell) to check for commonly misspelled words.
In the event of a false positive, the problematic word should be added, in all lowercase, to the `ignore-words-list` field of `./.codespellrc`. Regardless of the case of the word in the false positive, it must be in all lowercase in the ignore list. The ignore list is comma-separated with no spaces.
> Add CI workflow to check for commonly misspelled words

- api/Common.h
Current version does not wrap arguments in "()", so works incorrectly when used like this:
```
bitWrite(var, bit, cond?1:0);
```
Fixes #153
> Fix bitWrite with parenthesis

- api/Common.h
Not every MCU offers open drain pins, but some do. This change
means that they'll no longer have to play games to implement an
API-compatible pinMode() function that offers open drain.
Fixes #155
If you're reading this commit message because you need to add another
pin mode to this enum, the hacky trivial workaround is to do something
like this in your core:
```
// This typedef is used to extend the PinMode typedef enum
// in the ArduinoAPI, since they don't have contants
typedef enum {
INPUT_ANALOG = 99 , // We assume that the Arduino core will never have 99 PinModes
OUTPUT_OPEN_DRAIN   // It'd be cleaner to be able to count the size of that enum
} PinModeExtension;
```
Because PinMode is an enum and not a proper type, the compiler will
let the user pass either a PinMode or a …
> Add a new 'OUTPUT_OPENDRAIN' pinmode for platforms.

- README.md
The link in the README was still pointing to a development branch.
> Fix: ArduinoCore-samd:master has already been ported to using ArduinoCore-API.

- api/IPAddress.cpp
- api/IPAddress.h
- test/CMakeLists.txt
- test/src/IPAddress/test_IPAddress6.cpp
- test/src/IPAddress/test_fromString6.cpp
- test/src/IPAddress/test_operator_assignment.cpp
- test/src/IPAddress/test_operator_comparison6.cpp
- test/src/IPAddress/test_operator_parentheses.cpp
- test/src/IPAddress/test_operator_parentheses6.cpp
- test/src/IPAddress/test_printTo6.cpp
Some suggested code to add support for IPv6 to the IPAddress class. (Issue #168 )
The public interface changes are minimal:
- add a type() getter and corresponding enum
- add three new constructors: one for 16 octets, empty with type specifier, and byte pointer with type specifier
- add constant for IP6ADDR_ANY (similar function as IPADDR_NONE)
The changes are backward compatible. All of the IPv4 test cases continue to pass without any changes. i.e. Any IPv4 code will continue to get the same outputs for a given inputs.
Test cases added to cover IPv6.
Note: Whilst backwards compatible, this change does increase the memory footprint from 4 bytes to 20 bytes (assuming the enum compiles as an underlying int32_t, I think).
> Add IPv6 support to IPAddress

- README.md
These build instructions were reverse engineered out of the github actions (diving into arduino/cpp-test-action).
I think the dependencies are correct, but my machine already had a bunch of software installed, so I'm not sure (but it is a start).
This is useful for someone who wants to contribute to the repo, to run the host-based tests locally (before submitting).
(Note: I also had to make a minor change in `catch.hpp`, to set `sigStackSize = 32768`, as `MINSIGSTKSZ` was no longer defined (some kind of version incompatibility). I have not checked that change in.)
> Add some basic build instructions to run unit tests

- api/WCharacter.h
- test/CMakeLists.txt
- test/external/catch/v2.13.9/include/catch.hpp
- test/src/WCharacter/test_isAscii.cpp
- test/src/WCharacter/test_toAscii.cpp
@DhruvaG2000 
@beriberikix
@carlosperate
@matthijskooijman
> isAscii: avoid dependency on _GNU_SOURCE

- README.md
This fixes https://github.com/arduino/ArduinoCore-API/issues/96.
Depends on https://github.com/arduino/ArduinoCore-samd/pull/676.
> Fix: Providing documentation for various cores how to manually integrate ArduinoCore-API.

- test/CMakeLists.txt
- test/src/String/test_characterAccessFunc.cpp
- Fixes a stack buffer overflow in the `[String-getBytes-02]` test.
- Fixes the concatenation of the `CMAKE_{C,CXX}_FLAGS` variable in `test/CMakeLists.txt` (string concatenation instead of list concatenation).
This was caught by the GCC sanitizers. It might be a good idea to run the tests with `-fsanitize=address,undefined` in the CI (in addition to Valgrind) to catch these kinds of bugs early.
> Fix stack buffer overflow in String::getBytes() test

- api/RingBuffer.h
C++20 deprecated the use of increment/decrement with volatile variables. This PR avoids the compiler warning at that language level or later.
> Fix volatile errors when compiling for C++23

- api/String.cpp
- test/src/String/test_replace.cpp
This pr fixes `string::replace` not replacing multiple occurrences of longer string with shorter one.
I also included unit tests from the issue
This fixes #199
> Fixed string::replace doesn't replace multiple occurrences of longer string with shorter one 

- api/CanMsg.h
Reproducible with an empty sketch:
```
// my_example.ino
void setup()
{
}
void loop()
{
}
```
Compiled with:
```
arduino-cli compile --build-property compiler.cpp.extra_flags='-Wno-unused-parameter -Werror' --fqbn arduino:mbed_nano:nano33ble --log-level trace --verbose --warnings all my_example/my_example.ino
```
Tail of the output:
```
In file included from /home/hroche/.arduino15/packages/arduino/hardware/mbed_nano/4.0.4/cores/arduino/api/CanMsgRingbuffer.h:17:0,
from /home/hroche/.arduino15/packages/arduino/hardware/mbed_nano/4.0.4/cores/arduino/api/CanMsgRingbuffer.cpp:12:
/home/hroche/.arduino15/packages/arduino/hardware/mbed_nano/4.0.4/cores/arduino/api/CanMsg.h: In member function 'virtual size_t arduino::CanMsg::printTo(arduino::Print&) const': …
```
> Fix format specifier for printing CAN message ID in CanMsg.h.

- api/Print.cpp
- test/src/Print/test_print.cpp
> Fix of empty string printed in case of a 64-bit unsigned integer.

- .github/workflows/unit-tests.yml
The codecov-action [is deprecated](https://github.com/codecov/codecov-action#%EF%B8%8F--deprecation-of-v1).
Try to use the token to solve this https://github.com/codecov/codecov-action/issues/557#issuecomment-1224970469
> Bump codecov-action to v3, and use token

- test/src/String/test_compareTo.cpp
Fix for issue #204 where the test suite fails intermittently on some platforms.
> Do not rely on the actual value returned from strcmp in tests, only the sign.

- test/src/WCharacter/test_toAscii.cpp
Fix for #197 by removing undef of _GNU_SOURCE.
Change includes PR #205 so I can run the test suite reliably.
> Test to ascii

- api/CanMsgRingbuffer.cpp
- test/CMakeLists.txt
- test/src/CanMsgRingbuffer/test_available.cpp
Fixes a deprecated use of volatile in CanMsgRingbuffer.
Also added a basic testcase to make sure the CPP file is compiled/tested.
Relies on PR #206 to reliably run the tests under C++20
> Fix: add test case for CanMsgRingBuffer.

- .github/ISSUE_TEMPLATE/api-deprecation.md
- .github/ISSUE_TEMPLATE/api-improvement.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/new-api-component.md
- .github/ISSUE_TEMPLATE/other-enhancement.md
A menu of issue categories will be presented when the user begins the issue creation process.
The issue will be prefilled with prompts for the specific information needed for each issue type.
If none of the issue types are applicable, the user can click the "Open a blank issue" link at the bottom of the issue template chooser page to get the previous issue creation behavior.
The [default organization level security policy](https://github.com/arduino/.github/blob/master/SECURITY.md) is linked to for people wanting to report a security vulnerability.
Links are provided to the Arduino Language Reference, Arduino Forum, and Arduino Developers Mailing list to redirect support requests.
---
---
---
References:
- https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-r …
> Add issue templates

- README.md
After the discussion in #213, I thought it would be helpful to state in the documentation the version of the language that a core needs to support in order to use the API. It also makes it clearer to contributors which language level they must stick to.
> Document that C++11 is required

- api/HardwareCAN.h
Add documentation to the API methods, to clarify order of message transmission and define other behaviours.
> Add documentation for CAN API to fix #221

- api/CanMsg.h
`other.data` will never be null, triggering a compilation error with the test cases on GCC-13 or CLang 15.0.0
> Fix #217 when compiling with newer compiler versions

- api/String.h
- test/src/String/test_isEmpty.cpp
This PR adds a tiny inline `isEmpty()` method to the String class. This is borrowed from the ESP32 core which made it popular.
> Add String::isEmpty()

- api/deprecated-avr-comp/avr/pgmspace.h
These two macros were missing so i added them
> Added two missing macros to the compatibility pgmspace.h

- api/DMAPool.h
The `DMAPool` class allocates and manages a pool of buffers that are DMA and cache-friendly, designed for applications that require frequent buffer exchanges between the CPU and DMA (such as audio applications).
The `DMAPool` maintains a read and write queues of DMA buffers. DMA buffers' sizes are rounded up to a multiple of the pool's alignment (which defaults to cache line size on platforms with caches), and their memory is initialized from one contiguous memory block.
A typical usage of `DMAPool` involves allocating a DMA buffer from the write queue for writing by a producer, updating its contents, and then releasing it. When released, the DMA buffer returns to the pool, which in turn places it back into the read queue for later consumption by the consumer. For example:
```C++
// …
```
> api: Add DMAPool.
